openapi: 3.0.3
info:
  title: jtbt2-fav-color
  description: An API for favorite colors
  version: 1.0.0

x-mock-implemented: true
paths:
  /foo:
    x-controller: foo
    get:
      x-operation: getFoo
      responses:
        200:
          description: foo bar
          content:
            application/json:
              schema:
                properties:
                  bar:
                    type: string

  /:
    x-controller: main
    get:
      description: List favorite colors (can filter by color)
      x-operation: listFavoriteColors
      responses:
        200:
          description: PersonFavoriteColor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoriteColorList'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
    post:
      summary: Add a new student's favorite color
      x-operation: addFavoriteColor
      requestBody:
        description: byuId, favoriteColor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/favoriteColorObjectById'
        required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'

  /{byuId}:
    x-controller: byuId
    get:
      description: Get student's favorite color
      x-operation: getFavoriteColor
      parameters:
        - $ref: '#/components/parameters/byuIdParam'
      responses:
        200:
          description: PersonFavoriteColor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/favoriteColorObject'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'

    put:
      description: Update student's favorite color
      x-operation: updateFavoriteColor
      parameters:
        - $ref: '#/components/parameters/byuIdParam'
      requestBody:
        description: favoriteColor
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/favoriteColorObject'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
    delete:
      description: Remove student's favorite color
      x-operation: removeFavoriteColor
      parameters:
        - $ref: '#/components/parameters/byuIdParam'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'

components:
  schemas:
    byuId:
      type: string
      example: '123456789'
    favoriteColor:
      type: string
      example: 'red'
    favoriteColorObject:
      type: object
      properties:
        favoriteColor:
          $ref: '#/components/schemas/favoriteColor'
    favoriteColorObjectById:
      type: object
      properties:
        byuId:
          $ref: '#/components/schemas/byuId'
        favoriteColor:
          $ref: '#/components/schemas/favoriteColor'
    FavoriteColorList:
      type: array
      items:
        $ref: '#/components/schemas/favoriteColorObjectById'
    response:
      type: object
      properties:
        result:
          type: string
          example: 'success'
  parameters:
    byuIdParam:
      name: byuId
      in: path
      description: a BYU Id
      required: true
      schema:
        $ref: '#/components/schemas/byuId'
